import localFont from "next/font/local";
import "./globals.css";
import Auth from "@/components/Auth";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="dark" >
			<body
				className={`${geistSans.variable} ${geistMono.variable} bg-primary-bg text-typography antialiased`}>
				<Auth>{children}</Auth>
			</body>
		</html>
	);
}









